### ISSUE TITLE
tasks failing when connection: local is specified

### ISSUE THREAD

**Issue by privateip** [arista-eosplus/ansible-eos#2]
the install required libraries and dependencies task is failing when connection is local

```
TASK: [arista.eos | install required libraries and dependencies] **************
failed: [veos01] => (item=eapilib-0.1.0.tar.gz) => {"cmd": "/usr/bin/pip install eapilib-0.1.0.tar.gz", "failed": true, "item": "eapilib-0.1.0.tar.gz"}
msg: stdout: Requirement 'eapilib-0.1.0.tar.gz' looks like a filename, but the file does not exist
Unpacking ./eapilib-0.1.0.tar.gz
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 126, in main
#
    self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 223, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 955, in prepare_files
    self.unpack_url(url, location, self.is_download)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1068, in unpack_url
    return unpack_file_url(link, location)
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 304, in unpack_file_url
    unpack_file(source, location, content_type, link)
  File "/usr/lib/python2.7/dist-packages/pip/util.py", line 466, in unpack_file
    or tarfile.is_tarfile(filename)
  File "/usr/lib/python2.7/tarfile.py", line 2583, in is_tarfile
    t = open(name)
  File "/usr/lib/python2.7/tarfile.py", line 1660, in open
    return func(name, "r", fileobj, **kwargs)
  File "/usr/lib/python2.7/tarfile.py", line 1722, in gzopen
    fileobj = bltn_open(name, mode + "b")
IOError: [Errno 2] No such file or directory: '/tmp/eapilib-0.1.0.tar.gz'

Storing complete log in /root/.pip/pip.log


FATAL: all hosts have already failed -- aborting
```

**Comment by privateip** [comment]
This is fixed with the move to pyeapi (http://github.com/arista-eosplus/pyeapi).  All current modules will be refactored to this implementation for 1.0
