### ISSUE TITLE
eos_ping fails when network is unreachable

### ISSUE THREAD

**Issue by phil-arista** [arista-eosplus/ansible-eos#52]
Regex fails when network is unreachable since the expected stdout isn't present.  Rather, the CLI just prints:

```
teststring#ping 10.0.0.1 repeat 10
connect: Network is unreachable
```

Here's what the failed play looks like:
```
TASK: [ping localhost] ******************************************************** 
failed: [veos_test_04] => {"failed": true, "parsed": false}
Traceback (most recent call last):
  File "/Users/phil/.ansible/tmp/ansible-tmp-1439551411.13-170914802501018/eos_ping", line 2079, in <module>
    main()
  File "/Users/phil/.ansible/tmp/ansible-tmp-1439551411.13-170914802501018/eos_ping", line 2063, in main
    (tx, rx, err, loss) = stats.groups()
AttributeError: 'NoneType' object has no attribute 'groups'

failed: [veos_test_03] => {"failed": true, "parsed": false}
Traceback (most recent call last):
  File "/Users/phil/.ansible/tmp/ansible-tmp-1439551411.13-86981380524970/eos_ping", line 2079, in <module>
    main()
  File "/Users/phil/.ansible/tmp/ansible-tmp-1439551411.13-86981380524970/eos_ping", line 2063, in main
    (tx, rx, err, loss) = stats.groups()
AttributeError: 'NoneType' object has no attribute 'groups'


FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/Users/phil/demo-ping.retry

veos_test_03               : ok=0    changed=0    unreachable=0    failed=1   
veos_test_04               : ok=0    changed=0    unreachable=0    failed=1   
```

**Comment by phil-arista** [comment]
Fixed in https://github.com/arista-eosplus/ansible-eos/commit/c7032a1a80aeb7cec4e87c1492b2163e2140fd7c

**Comment by phil-arista** [comment]
Release Note:
The eos_ping module will now successfully exit even when the ping result is ``network unreachable``
